version: '3.8'


services:
  avitoDb:
    image: postgres:13
    container_name: avitoDb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 3s
    ports:
      - "5432:5432"
    volumes:
      - './avito-postgres/local/postgre:/var/lib/postgresql/data/'
      - './avito-postgres/local/data:/data'

  migrator:
    image: migrate/migrate:latest
    volumes:
      - ./migrations:/migrations
    depends_on:
      avitoDb:
        condition: service_healthy
    command: ["-path=/migrations", "-database=postgres://user:password@avitoDb:5432/dbname?sslmode=disable", "up"]


  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      avitoDb:
        condition: service_healthy
    environment:
      SERVER_ADDRESS: 0.0.0.0:8080
      POSTGRES_CONN: postgresql://user:password@avitoDb:5432/dbname?sslmode=disable
    volumes:
      - .env:/app/.env

